import { BuddyTone } from './chatter-tone'

/**
 * Everything the buddy can say, by tone.
 *
 * A hundred each, in their own file, because the list is the feature: with eight
 * lines you hear them all in a morning and the joke dies of repetition. A hundred
 * a tone is what lets the cooldown be short — at ten seconds it can afford to
 * speak often, and still take weeks of steady use before anything comes round
 * twice.
 *
 * Every line is short enough for the bubble, and a test enforces that rather than
 * trusting anyone to count. Snarky is cheek about the work — the branch, the
 * diff, the hour it was committed at — and never about the competence of the
 * person reading it. A companion that implies you are bad at your job is one
 * somebody will rightly switch off, and it would deserve it.
 */
export const ChatterLines: {
  readonly [key in BuddyTone]: ReadonlyArray<string>
} = {
  [BuddyTone.Kind]: [
    'This is going well.',
    'Whatever you decide, I am behind you.',
    'You have got this.',
    'Nice and steady.',
    'I like it when you tidy up.',
    'Take your time with that one.',
    'Good spot.',
    'Proud of this release, honestly.',
    'That looks much better.',
    'You are doing fine.',
    'Small steps count.',
    'I would have missed that.',
    'Careful work, this.',
    'No rush from me.',
    'That is a kind commit message.',
    'Everything is where it should be.',
    'You thought about that one.',
    'I like this branch.',
    'Tidy.',
    'Someone has been looking after this.',
    'That was the hard part.',
    'The worst of it is behind you.',
    'Nearly there.',
    'Good decision.',
    'I trust your judgement.',
    'You checked. That matters.',
    'A quiet release is a good release.',
    'Nothing on fire today.',
    'That is one less thing.',
    'You can stop for tea after this.',
    'Well handled.',
    'I was hoping you would do that.',
    'Better than yesterday.',
    'Lovely.',
    'Steady hands.',
    'That will help somebody later.',
    'Future you says thank you.',
    'Somebody will read that and smile.',
    'Worth doing properly.',
    'You noticed. Good.',
    'A sensible order to do things in.',
    'No shortcuts. I approve.',
    'That is the careful way.',
    'Slow is fine.',
    'It is holding together nicely.',
    'Everything green.',
    'That is a relief.',
    'You have earned that one.',
    'Have a stretch.',
    'Do not forget to eat.',
    'It is going to be fine.',
    'I believe in this release.',
    'Nothing here worries me.',
    'You are further than you think.',
    'That is progress.',
    'One thing at a time.',
    'You can always come back to it.',
    'Perfectly reasonable.',
    'That will do nicely.',
    'Sensible.',
    'Good instinct.',
    'I like how you named that.',
    'Clear as anything.',
    'Somebody could follow this.',
    'That reads well.',
    'You made it simpler.',
    'Less than there was. Good.',
    'Neat.',
    'Honest work.',
    'Solid.',
    'That is safe.',
    'Nothing risky about that.',
    'Sleep well tonight.',
    'Friday can wait.',
    'There is no hurry.',
    'You have thought this through.',
    'A good place to stop.',
    'Come back to it fresh.',
    'That was patient of you.',
    'I noticed you double checked.',
    'Careful is not slow.',
    'That is the right call.',
    'Trust that.',
    'You know this code.',
    'Been here before, have you.',
    'Familiar ground.',
    'This part suits you.',
    'You are in a good rhythm.',
    'Keep going.',
    'Almost done.',
    'Last stretch.',
    'That is the tidy option.',
    'Good housekeeping.',
    'The branch looks healthy.',
    'Everything accounted for.',
    'Nothing stranded.',
    'All present.',
    'That is thorough.',
    'You left it better.',
    'Thank you for that one.',
  ],

  [BuddyTone.Dry]: [
    'Noted.',
    'That is one way to do it.',
    'Hm.',
    'Interesting choice.',
    'I will pretend I understood that.',
    'Carry on.',
    'Someone has been busy.',
    'The branch looks about right.',
    'Right.',
    'If you say so.',
    'Sure.',
    'That happened.',
    'Understood.',
    'I see it.',
    'Logged.',
    'Fine.',
    'Acceptable.',
    'Could be worse.',
    'Could be better.',
    'Neither here nor there.',
    'As expected.',
    'Predictable.',
    'No surprises.',
    'Same as last time.',
    'Again, then.',
    'Still going.',
    'Numbers went up.',
    'Numbers went down.',
    'Something changed.',
    'A change was made.',
    'Committed.',
    'Filed.',
    'Recorded.',
    'Duly noted.',
    'Observed.',
    'I saw that.',
    'Watching.',
    'Continue.',
    'Proceed.',
    'Very well.',
    'Adequate.',
    'Functional.',
    'It works, apparently.',
    'The tests will decide.',
    'We shall see.',
    'Time will tell.',
    'Probably fine.',
    'Likely harmless.',
    'Reasonable, on balance.',
    'Defensible.',
    'Justifiable.',
    'Within tolerance.',
    'Close enough.',
    'Roughly right.',
    'Approximately correct.',
    'In the right area.',
    'Not wrong.',
    'Not obviously wrong.',
    'No comment.',
    'I have no strong feelings.',
    'Whatever suits.',
    'Your call.',
    'Up to you.',
    'Either would do.',
    'Six of one.',
    'Makes little difference.',
    'Marginal.',
    'Incremental.',
    'Steady as she goes.',
    'On track, presumably.',
    'Roughly on schedule.',
    'The usual.',
    'Business as usual.',
    'Another day.',
    'Another branch.',
    'Another commit.',
    'The pile grows.',
    'More of it.',
    'That is a lot of files.',
    'That is not many files.',
    'Short one.',
    'Long one.',
    'Busy in here.',
    'Quiet in here.',
    'Development moves on.',
    'Production sits waiting.',
    'The release is where it was.',
    'Nothing has caught fire.',
    'Still no conflicts.',
    'Conflicts eventually, probably.',
    'Someone will merge that.',
    'It will need a review.',
    'Somebody should look at that.',
    'A decision was made.',
    'History will record it.',
    'Git remembers.',
    'It is in the log now.',
    'Permanent, that.',
    'Written down.',
    'Done is done.',
  ],

  [BuddyTone.Snarky]: [
    'Bold.',
    'Shipping on a Friday, are we?',
    'I would not have done that, but go on.',
    'Careful, it is almost working.',
    'Another one? Already?',
    'I am telling development about this.',
    'That is going straight into production, is it.',
    'You clicked it. I saw you.',
    'Brave.',
    'Living dangerously.',
    'That will be fine, probably.',
    'No tests, no problem.',
    'The build will love that.',
    'Someone will find out on Monday.',
    'Ship it. What could happen.',
    'That is a future problem.',
    'Leave it for the next person.',
    'I have seen worse. Not often.',
    'Ambitious.',
    'Optimistic.',
    'Confident, that.',
    'That is a choice.',
    'Committing to it, then.',
    'No going back now.',
    'Production will remember this.',
    'Hope you like being on call.',
    'I am not signing off on that.',
    'Do not blame me.',
    'I was not consulted.',
    'For the record, I said nothing.',
    'My paws are clean.',
    'I will be over here.',
    'Good luck with the review.',
    'Reviewers will enjoy that.',
    'That diff is a journey.',
    'Someone is going to ask about that.',
    'Explain that one at standup.',
    'Cannot wait to read the commit message.',
    'Riveting commit message.',
    'Very descriptive.',
    'The branch name says it all.',
    'Merging on a whim, are we.',
    'That is one big merge.',
    'Conflicts incoming.',
    'I smell a revert.',
    'Save your work.',
    'Have you tried it first?',
    'Tested locally, obviously.',
    'Works on your machine.',
    'It compiled. That is something.',
    'Green does not mean correct.',
    'The tests are being polite.',
    'Coverage is a state of mind.',
    'Nobody reads the changelog anyway.',
    'Documentation? In this economy?',
    'Comments are for other people.',
    'Self documenting, is it.',
    'Future you is going to love this.',
    'Somebody will inherit that.',
    'That is job security.',
    'Impressive nesting.',
    'That function has range.',
    'It does a lot, that one.',
    'Single responsibility, allegedly.',
    'Refactor next sprint, sure.',
    'A TODO. How permanent.',
    'Temporary, is it.',
    'Nothing lasts like a workaround.',
    'That has been there for years.',
    'Load bearing, that comment.',
    'Do not touch it and it will be fine.',
    'Ah, the old approach.',
    'Classic.',
    'Vintage.',
    'Nostalgic, this code.',
    'Someone was in a hurry.',
    'Written at five o clock, that.',
    'Friday afternoon code.',
    'Monday morning code.',
    'Committed before coffee.',
    'That is a caffeine decision.',
    'Sleep on it. Or do not.',
    'Second thoughts? No? Fine.',
    'You are sure about this.',
    'Absolutely certain, are you.',
    'No hesitation at all.',
    'Straight in.',
    'Not even a pause.',
    'Decisive. Terrifying.',
    'I respect the commitment.',
    'Well, that is done now.',
    'You cannot unship it.',
    'The tag is permanent.',
    'Version numbers only go up.',
    'Somewhere a pipeline is crying.',
    'The build server has feelings.',
    'I hope the pipeline is in a good mood.',
    'Fingers crossed, then.',
    'This is going to be interesting.',
    'Anyway, I am sure it is fine.',
  ],
}
